// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1982.Robot2016.subsystems;

import edu.wpi.first.wpilibj.Encoder;

import org.usfirst.frc1982.Robot2016.Robot;
import org.usfirst.frc1982.Robot2016.RobotMap;
import org.usfirst.frc1982.Robot2016.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveSystem extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController leftMotor = RobotMap.driveSystemLeftMotor;
    private final SpeedController rightMotor = RobotMap.driveSystemRightMotor;
    private final RobotDrive robotDrive = RobotMap.driveSystemRobotDrive;
    private final Encoder leftEncoder = RobotMap.driveSystemLeftEncoder;
    private final Encoder rightEncoder = RobotMap.driveSystemRightEncoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new DriveEnable());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public void driveNow(Joystick js){
    	//if the robot is facing forward,
    	if (!Robot.reversed) {
    		//may change depending on axis for joy-stick
    		//drive forward
    		robotDrive.arcadeDrive(js.getY(),js.getX());
    	//if the robot is facing backward,
    	} else {
    		robotDrive.arcadeDrive(-js.getY(),-js.getX());
    	}
    }
    
    public void testAxes(Joystick js) {
    	System.out.println("X axis: " + js.getX()); //get the X axis and print it to the console
    	System.out.println("Y axis: " + js.getY()); //same here, but Y
    	System.out.println("Z axis: " + js.getZ()); //^ but Z
    	System.out.println("Throttle axis: " + js.getThrottle()); //^ but Throttle
    	System.out.println("Twist axis: " + js.getTwist()); //^ but Twist
    }
    
    public void driveDistance(double feet){
    	double error = (feet-leftEncoder.getDistance())/10.0;
    	if(Math.abs(error) > 1)
    		error = error/Math.abs(error);
    	robotDrive.drive(error, 0);
    	
    		
    }
}

