// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1982.Robot2016;

import org.usfirst.frc1982.Robot2016.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton toggleCamButton1;
    public JoystickButton toggleRoller2;
    public JoystickButton winchManual3;
    public JoystickButton sliderForward4;
    public JoystickButton sliderBack6;
    public JoystickButton sliderOff5;
    public JoystickButton armOff5;
    public Joystick driverJoystick;
    public Joystick operatorBoard;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        operatorBoard = new Joystick(1);
        
        driverJoystick = new Joystick(0);
        
        armOff5 = new JoystickButton(driverJoystick, 5);
        armOff5.whenPressed(new ArmOff());
        sliderOff5 = new JoystickButton(driverJoystick, 5);
        sliderOff5.whenPressed(new SetSliderBall());
        sliderBack6 = new JoystickButton(driverJoystick, 6);
        sliderBack6.whenPressed(new SetSliderBack());
        sliderForward4 = new JoystickButton(driverJoystick, 4);
        sliderForward4.whenPressed(new SetSliderForward());
        winchManual3 = new JoystickButton(driverJoystick, 3);
        winchManual3.whenPressed(new WinchManual());
        toggleRoller2 = new JoystickButton(driverJoystick, 2);
        toggleRoller2.whenPressed(new ToggleRoller());
        toggleCamButton1 = new JoystickButton(driverJoystick, 1);
        toggleCamButton1.whenPressed(new ToggleCameraComm());


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("DriveEnable", new DriveEnable());
        SmartDashboard.putData("ToggleRoller", new ToggleRoller());
        SmartDashboard.putData("SetSliderForward", new SetSliderForward());
        SmartDashboard.putData("SetSliderBack", new SetSliderBack());
        SmartDashboard.putData("SetSliderBall", new SetSliderBall());
        SmartDashboard.putData("ToggleCameraComm", new ToggleCameraComm());
        SmartDashboard.putData("ArmUp", new ArmUp());
        SmartDashboard.putData("ArmDown", new ArmDown());
        SmartDashboard.putData("ArmOff", new ArmOff());
        SmartDashboard.putData("WinchManual", new WinchManual());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getDriverJoystick() {
        return driverJoystick;
    }

    public Joystick getOperatorBoard() {
        return operatorBoard;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

